# Generated by Django 5.2.7 on 2025-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_headline',
            field=models.BooleanField(default=False, verbose_name='Tampilkan di Headline'),
        ),
    ]
