# Generated by Django 5.2.7 on 2025-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True),
        ),
    ]
