# Generated by Django 5.2.7 on 2025-11-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
