# Generated by Django 5.2.7 on 2025-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_article_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='articles', to='app.topic'),
        ),
    ]
