# Generated by Django 5.2.7 on 2025-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_topic_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan Gambar'),
        ),
    ]
