# Generated by Django 5.2.7 on 2025-11-09 14:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_article_published_at_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default=1, upload_to=app.models.rename_featured_image),
            preserve_default=False,
        ),
    ]
